version: 2

sources:
    - name: staging
      #For bigquery:
      database: level-agent-375808
      schema: nyc_trips_test

      # loaded_at_field: record_loaded_at
      tables:
        - name: green_taxi
        - name: yellow_taxi
         # freshness:
           # error_after: {count: 6, period: hour}